spring:
  application:
    name: orderClient
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lewis
    url: jdbc:mysql://192.168.2.2:3306/springcloud_sells?useUnicode=true&characterEncoding=UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
